@startuml dev-test-prod

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/devicons/code.puml
!includeurl ICONURL/devicons/dropbox.puml
!includeurl ICONURL/font-awesome/cogs.puml
!includeurl ICONURL/font-awesome-5/play.puml
!includeurl ICONURL/devicons2/vscode.puml

HIDE_STEREOTYPE()

Component(codeAlias, "Code", $sprite="code")
Component(buildAlias, "Build", $sprite="cogs")
Component(artifactAlias, "Artifact", "image", $sprite="dropbox")

System_Boundary(c1, "Runtime") {
    Container(devAlias, "Dev", "env", $sprite="play")
    Container(testAlias, "Test", "env", $sprite="play")
    Container(prodAlias, "Production", "env", $sprite="play")
}

Rel_U(devAlias, testAlias, " ")
Rel_U(testAlias, prodAlias, " ")
Rel_R(codeAlias, buildAlias, " ")
Rel_R(buildAlias, artifactAlias, " ")
Rel_R(artifactAlias, devAlias, "deploy")
' Rel_R(artifactAlias, testAlias, "deploy")
' Rel_R(artifactAlias, prodAlias, "deploy")

@enduml